language: r
warnings_are_errors: true
sudo: required

matrix:
    include:
        - r: release
          os: linux
          dist: trusty # 14.04; default
          env: R_CODECOV=true
          #- r: release
          #os: osx
          #brew_packages: gdal2
          #- r: oldrel
          #env: DEPS=cran
          #os: linux
          #- r: oldrel
          #env: DEPS=cran
          #os: osx
          #- r: devel
          #env: DEPS=cran
          #os: linux
          #- r: devel
          #env: DEPS=cran
          #os: osx

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
